
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # ro: 읽기 전용
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  
      - ./nginx/conf.d:/etc/nginx/conf.d:ro 
    depends_on:
      - frontend
      - backend

  frontend:
    image: node:18-alpine
    container_name: frontend
    working_dir: /app
    command: sh -c "echo '<h1>Hello from Frontend</h1>' > index.html && npx http-server -p 3000"
    expose:
      - "3000"

  backend:
    # Dockerfile로 백엔드 프로젝트를 이미지로 빌드
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    # 빌드한 이미지의 이름 설
    image: ${SPRING_IMAGE_NAME}:latest
    container_name: ${SPRING_CONTAINER_NAME}
    restart: always
    environment:
      SPRING_CONTAINER_PORT: ${SPRING_CONTAINER_PORT}
    expose:
      - "${SPRING_CONTAINER_PORT}"
      
networks:
  default:
    external: true
    name: app-network

