services:
  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    # 빌드한 이미지의 이름 설정
    image: ${NEXTJS_DEV_IMAGE_NAME}
    container_name: ${NEXTJS_DEV_CONTAINER_NAME}
    restart: always
    expose:
      - "${NEXTJS_DEV_CONTAINER_PORT}"
    # 운영환경 명시 : 항상 production으로 설정(성능 저하 방지)
    environment:
    - NODE_ENV=production
    - PORT=${NEXTJS_DEV_CONTAINER_PORT}

  backend:
    # Dockerfile로 백엔드 프로젝트를 이미지로 빌드
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    # 빌드한 이미지의 이름 설정정
    image: ${SPRING_DEV_IMAGE_NAME}
    container_name: ${SPRING_DEV_CONTAINER_NAME}
    restart: always
    environment:
      SPRING_CONTAINER_PORT: ${SPRING_DEV_CONTAINER_PORT}
    expose:
      - "${SPRING_DEV_CONTAINER_PORT}"
    volumes:
      - /home/ubuntu/aws:/app/aws

networks:
  default:
    external: true
    name: app-network
