
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # ro: 읽기 전용
      - /home/ubuntu/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro

    depends_on:
      - frontend
      - backend

      
  frontend:
    image: node:18-alpine
    container_name: frontend
    working_dir: /app
    command: sh -c "echo '<h1>Hello from Frontend</h1>' > index.html && npx http-server -p 3000"
    expose:
      - "3000"

  backend:
    # Dockerfile로 백엔드 프로젝트를 이미지로 빌드
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    # 빌드한 이미지의 이름 설
    image: spring-project:latest
    container_name: spring-container
    restart: always
    environment:
      SPRING_CONTAINER_PORT: 8080
    expose:
      - "8080"
    volumes:
      - /home/ubuntu/aws:/app/aws
      
networks:
  default:
    external: true
    name: app-network
