services:
  frontend-dev:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    # 빌드한 이미지의 이름 설정
    image: nextjs-dev:latest
    container_name: nextjs-dev-container
    restart: always
#	    expose:
#      - "3000"
    ports: 
      - "3001:3001"
    # 운영환경 명시 : 항상 production으로 설정(성능 저하 방지)
    environment:
    - NODE_ENV=production

  backend-dev:
    # Dockerfile로 백엔드 프로젝트를 이미지로 빌드
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    # 빌드한 이미지의 이름 설
    image: spring-dev:latest
    container_name: spring-dev-container
    restart: always
    environment:
      SPRING_CONTAINER_PORT: 8080
#    expose:
#      - "8080"
    ports:
      - "8081:8081"
    volumes:
      - /home/ubuntu/aws:/app/aws

networks:
  default:
    external: true
    name: app-network
