server:
  servlet:
    context-path: /api/v1
  port: 8080

spring:
  application:
    name: fourcut
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fourcut?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  config:
    import: "optional:classpath:application-secret.yml"

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # none, update, create, create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect