server:
  servlet:
    context-path: /api/v1
  port: 8080

spring:
  application:
    name: fourcut

  config:
    import: optional:classpath:application-secret.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fourcut?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # none, update, create, create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "${KAKAO_CLIENT_ID}"  # 환경변수로 관리
            client-secret: "${KAKAO_CLIENT_SECRET}"  # 환경변수로 관리
            redirect-uri: "http://localhost:3000/api/v1/oauth/kakao/callback"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: kakao
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

kakao:
  logout-redirect-uri: http://localhost:8080/logout/success

jwt:
  secret: "${JWT_SECRET}"
  access:
    expiration: 3600000
  refresh:
    expiration: 604800000